/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.5.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.seittiffe.weather.ui.controller;

import javax.annotation.Generated;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.GetMapping;

import com.seittiffe.weather.ui.model.HealthCheckResponse;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-04-05T15:30:51.630808200-04:00[America/Santiago]")
@Validated
@Tag(name = "health-check", description = "the health-check API")
public interface HealthCheckApi {

	/**
	 * GET /health-check Check the health status of the weather API
	 *
	 * @return Health check consultation was successful (status code 200)
	 */
	@Operation(operationId = "getHealthCheck", description = "Check the health status of the weather API", responses = {
			@ApiResponse(responseCode = "200", description = "Health check consultation was successful", content = {
					@Content(mediaType = "application/json", schema = @Schema(implementation = HealthCheckResponse.class)) }) })
	@GetMapping(value = "/health-check", produces = { "application/json" })
	@CrossOrigin(origins = "http://localhost:3000")
	default ResponseEntity<HealthCheckResponse> getHealthCheck() {
		return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
	}

}
