/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (6.5.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.seittiffe.weather.ui.controller;

import javax.annotation.Generated;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.GetMapping;

import com.seittiffe.weather.ui.model.VersionResponse;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-04-05T15:30:51.630808200-04:00[America/Santiago]")
@Validated
@Tag(name = "version", description = "the version API")
public interface VersionApi {

	/**
	 * GET /version Check the version the weather API
	 *
	 * @return API version consultation was successful (status code 200)
	 */
	@Operation(operationId = "getVersion", description = "Check the version the weather API", responses = {
			@ApiResponse(responseCode = "200", description = "API version consultation was sucessful", content = {
					@Content(mediaType = "application/json", schema = @Schema(implementation = VersionResponse.class)) }) })
	@GetMapping(value = "/version", produces = { "application/json" })
	default ResponseEntity<VersionResponse> getVersion() {
		return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);
	}

}
